### ISSUE TITLE
data sorting not fully correct

### ISSUE THREAD

**Issue by sebastianelsner** [tigra564/pgdump-sort#3]
The data sections are not fully sorted if they contain numbers, since "sorted()" does not do a natural sort.

I replaced the sorted() calls with calls to natsort.natsorted() and I got the correct and reproducible output.

natsort can be installed via:

pip install natsort

**Comment by tigra564** [comment]
Hello Sebastian,

Could you provide a minimal example (SQL dump) showing the issue?

**Comment by tigra564** [comment]
Since I don't understand the problem stated adn there is no feedback for almost two weeks, I close the issue. Will reopen if information arrives.
